### PR TITLE
Fixed build uploads

### PR DESCRIPTION
**Pull request by rgaudin**
Changes the destination of uploads to master.download.kiwix.org on port 30022
As this service doesn't offer a shell anymore, converted the folder creation
and file renaming to more verbose, SFTP-based scripts.

### CODE REVIEW

**Comment by kelson42** [comment]
@rgaudin Can you rebase and merge please?

**Comment by kelson42** [comment]
I don't know for you, but the repository is huge (almost 3GB) and I can not rebase this branch because somehow the `master` branch is in an unusual state:
```
$ git reset --hard origin/master
HEAD is now at e45f1062 Fix version number rewriting to take account of SHA
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   AppPackages/KiwixWebApp_0.0.0.0_Test/Add-AppDevPackage.ps1
	modified:   www/img/icons/wikimed-lightblue-64.ico

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by rgaudin** [comment]
@kelson42 indeed the repo is very large and just pushing my changes was difficult 🙂
The repo is not in an unusal state though. It's just that those 2 files use windows line endings and  your git config (default) rewrites them to unix line endings. It's a windows project after all 😉

**Comment by Jaifroid** [comment]
@kelson42 @rgaudin I recently decided to try building the WikiMed and Wikivoyage apps on GitHub Actions, which involved pushing the ZIM archives (split into 50MB chunks) to their respective branches (this works very well, and the Electron versions of the custom apps build very fast on Actions and "upload" almost instantly to GitHub Releases, avoiding me having to use something like 5-6GB of my own bandwidth twice a month every time I release a new custom app for the multiple different platforms).

These chunks are not on master, and shouldn't have affected a PR based on master, depending on the checkout depth I guess. I intend to purge the respective branches before I push a new ZIM, so that I am not keeping a ridiculously large history of irrelevant changes.

I understand there is another solution using Large File Storage, which I could look into if Kiwix org has access to that.

**Comment by kelson42** [comment]
@Jaifroid ZIM files should be downloaded live by the build script, not being in the git. Kiwix Android custom does that way.

**Comment by Jaifroid** [comment]
Thanks once again, @rgaudin. @kelson42 I'll look into the solution you suggest.

**Comment by Jaifroid** [comment]
I made a few adjustments not directly related to this PR to fix some issues with how/when Electron builder publishes the app versions. Nightly runs should now exit cleanly if there was no error. Due to my experiments there are lots of packages appearing in the 6th April nightly folder, but rest assured that cron jobs will only produce one of each package going forwards.

**Pull request merged**
